const notesOne = {
    1: "You told me you really liked my good morning or good night messages. I hope this will put an even bigger smile on your face.",
    2: "After we spoke for the first time, I was already obsessed with your laugh and told everyone about it.",
    3: "I remember the first time you didn't respond when I went to bed. I was afraid you didn't like me. Glad I was just overthinking.",
    4: "You're the most amazing human I know. I hope I can make you feel that every day.",
    5: "I don't know what I did to deserve you, but I will make sure to never take you for granted.",
    6: "I hope with me you feel less alone.",
    7: "Whenever I see a notification from you, I can't help myself but smile.",
    8: "I can't wait to dance in the rain with you.",
    9: "I never thought that joking around would put me in a position to meet you. I'm very grateful that I did.",
    10: "Thank you for being part of my everyday life.",
    11: "Hearing you laugh makes me feel one hundred times better. In an instant.",
    12:" Everyday I keep falling for you. Each laugh, ragebait or regular conversation makes me fall more and more.",
    13: "The day I get to see your eyes in front of me, will be one of the best days of my life.",
    14: "Being with you makes the world brighter. I can't stop thanking you for that.",
    15: "You are my safe place and I hope I can be yours.",
    16: "You make me want to be a better person. Iam eternally grateful for that and for you.",
    17: "Annoying you online is fun, I can't even begin to imagine how fun it will be in person.",
    18: "You choosing to spend time with me makes me the luckiest person to ever exist.",
    19: "One day you will be able to see yourself how I see you.",
    20: "I will always be there for you. I will listen to any problem, any bad thought. You will not have to go through the bad times alone anymore.",
    21: "I will wrap that red scarf around you one day.",
};

const notesTwo = {
    1: "What is your favorite moment of the two of us?",
    2: "You make life less boring. You make it enjoyable and something to look forward to. You're the reason I feel joy again.",
    3: "How would a perfect day look like for you right now, under the current circumstances?",
    4: "Send me a song that pictures how you've been feeling lately.",
    5: "I get nervous when I think about finally meeting you. The good type of nervous. Like a little kid who can't wait for christmas to happen.",
    6: "How did you describe me to your friends when we started talking compared to now?",
    7: "You are the first thought I have  when I wake up and the last before I fall asleep. I think about you all the time.",
    8: "I love you more(This is the calendar of truths)",
    9: "I hope today will be as lovely as your smile, as your laugh. You deserve everyday to be the best day.",
    10: "Is there anything you are afraid of in terms of our future together?",
    11: "What is 'our song' for you?",
    12: "Never worry about being enough. Even at your lowest you are more than I ever thought I'd deserve. You are enough, everyday.",
    13: "Every day that I don't hear your voice is a bad day. I hope those day will never happen again.",
    14: "No compliment in this world could do you justice. You're more than beautiful. More than gorgeous. You are my everything.",
    15: "What do you like most about me and what should I do more of?",
    16: "I can't wait for the day to wake up next to you. It will almost be as good as holding you in my arms for the first time.",
    17: "Pick something you'd like to do this weekend. No matter what, we will do it.",
    18: "Is there anything you're afraid to tell me because you worry about my reaction?",
    19: "You make me feel less like a burden. Something that is so engraved in me and I thought would always be there is now cracking away, piece by piece.",
    20: "I know we aren't together yet,but in my heart we are. You have my heart for quite some time already.",
    21: "I love you. I love you so much. I remember the first time I said it. How nervous I was. The fear I had about you not feeling the same maybe. That I read the situation wrong. I'm so happy I didn't.",
};